media:
  input: uploads
  output: /uploads

content:
  # =========================
  # COLEÇÃO — TESTES
  # =========================
  - name: testes
    label: Testes
    type: collection
    path: content/testes
    filename: "{fields.title}.md"

    view:
      primary: title
      secondary: area
      sort: [area, title]

    fields:
      - name: title
        label: Nome do teste
        type: string
        required: true

      - name: area
        label: Área
        type: string
        options:
          values:
            - Hematologia
            - Imunologia / Autoimunidade
            - Microbiologia
            - Química Clínica
            - Citometria de Fluxo
            - Farmacocinética Avançada

      - name: metodo
        label: Método
        type: string

      - name: amostra
        label: Amostra
        type: string

      - name: material_colheita
        label: Material de Colheita
        type: string

      - name: descricao_clinica
        label: Descrição clínica
        type: rich-text

      - name: transporte_estabilidade
        label: Transporte/Estabilidade
        type: text

      - name: tempo_resposta
        label: Tempo de resposta
        type: string

      - name: setor
        label: Setor
        type: string

      - name: observacoes
        label: Observações importantes
        type: text


  # =========================
  # PÁGINAS FIXAS
  # =========================
  - name: inicio
    label: Página inicial
    type: file
    path: content/paginas/inicio.md

    fields:
      - { name: title, label: Título, type: string }
      - { name: description, label: Descrição curta, type: text }
      - { name: body, label: Conteúdo, type: rich-text }

  - name: sobre
    label: Sobre o serviço
    type: file
    path: content/paginas/sobre.md

    fields:
      - { name: title, label: Título, type: string }
      - { name: description, label: Descrição curta, type: text }
      - { name: body, label: Conteúdo, type: rich-text }

  - name: utentes
    label: Informações a utentes
    type: file
    path: content/paginas/utentes.md

    fields:
      - { name: title, label: Título, type: string }
      - { name: description, label: Descrição curta, type: text }
      - { name: body, label: Conteúdo, type: rich-text }

  - name: contactos
    label: Contactos
    type: file
    path: content/paginas/contactos.md

    fields:
      - { name: title, label: Título, type: string }
      - { name: description, label: Descrição curta, type: text }
      - { name: body, label: Conteúdo, type: rich-text }
