media:
  input: uploads
  output: /uploads

content:
  - name: testes
    label: Testes
    type: collection
    path: content/testes
    filename: "{fields.title}.md"

    fields:
      - name: title
        label: Nome do teste
        type: string

      - name: area
        label: Área
        type: select
        options:
          - Hematologia
          - Imunologia / Autoimunidade
          - Microbiologia
          - Química Clínica
          - Citometria de Fluxo
          - Farmacocinética Avançada

      - name: metodo
        label: Método
        type: string

      - name: amostra
        label: Amostra
        type: string

      - name: material_colheita
        label: Material de Colheita
        type: string

      - name: descricao_clinica
        label: Descrição clínica
        type: text

      - name: transporte_estabilidade
        label: Transporte/Estabilidade
        type: text

      - name: tempo_resposta
        label: Tempo de resposta
        type: string

      - name: setor
        label: Setor
        type: string

      - name: observacoes
        label: Observações importantes
        type: text

  - name: paginas
    label: Páginas
    type: collection
    path: content/paginas
    filename: "{fields.title}.md"

    fields:
      - name: title
        label: Título
        type: string

      - name: description
        label: Descrição curta
        type: text

      - name: body
        label: Conteúdo
        type: markdown
